name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build --file Dockerfile --tag e-commerce .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag e-commerce ik3232/e-commerce

        docker push ik3232/e-commerce


    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

      - name: Authenticate with Google Cloud
        run: echo "$GOOGLE_CREDENTIALS" > /tmp/credentials.json

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform apply -auto-approve